- cmd/ocm-metamodel-tool/check/cmd.go
- cmd/ocm-metamodel-tool/main.go
This patch adds to the tool a new `check` command that loads the model
but doesn't generate any code. This is inteded to be used in the jobs
that check pull requests for the model project.
> Add `check` command

- Makefile
This patch changes the _Makefile_ of the project so that the _cmds_
target doesn't copy the generated binaries to the `bin` directory of the
user, as that isn't possible in the Jenkins environment.
> Don't install binaries

- CHANGES.adoc
- pkg/info/info.go
> Release 0.0.3

- pr_check.sh
This patch changes the `pr_check.sh` script that runs in Jenkins so that
it installs the `goimports` tool that is needed to run the model tests.
> Install `goimports`

- pkg/generators/readers.go
- pkg/generators/servers.go
- tests/servers_test.go
1. In the current implementation we had disregarded the request query parameters, this patch fixes this issue.
2. This patch also adds tests to address this issue.
cc: @jhernand
> Parse request query arguments

- pkg/generators/servers.go
Currently the fields for server requests corresponding to query
parameters are generated using the same algorithm than the names of the
query parameters as used in the HTTP protocol. For example, if the name
of the parameter is `size` then the name of the field is also `size`.
But this will not work for parameter names with more than one word. For
example, if a new `MyParameter` is added then it will result in a field
name that is `my_parameter` instead of the expected `myParameter`. This
patch fixes that.
> Fix field name for query parameters

- CHANGES.adoc
- pkg/info/info.go
The more relevant changes in this version are the following:
- Fix generation of field names for query parameters.
- Remove `query` and `path` fields from request objects.
- Remove unused imports.
> Release 0.0.5

- pkg/generators/builders.go
- tests/builders_test.go
This patch adds to builders a new `Copy` method that can be used to copy
the contents of an existing object. For example, to create a copy of a
cluster and then change the name:
```go
// Get the original cluster:
original := ...
// Create the modified cluster copying the original and then changing
// the name:
modified, err := cmv1.NewCluster().
Copy(original).
Name("newname").
Build()
if err != nil {
...
}
```
> Add `Copy` method to builders

- pkg/concepts/attribute.go
- pkg/concepts/error.go
- pkg/concepts/locator.go
- pkg/concepts/method.go
- pkg/concepts/model.go
- pkg/concepts/parameter.go
- pkg/concepts/resource.go
- pkg/concepts/service.go
- pkg/concepts/type.go
- pkg/concepts/version.go
This patch changes the metamodel so that all list of concepts are always
kept sorted by name. This is intended to ensure that the generated code
doesn't change when the order of the concepts in the input chages, or
when the algorithms used internally to populate the metamodel change.
> Keep concepts sorted by name

- pkg/generators/clients.go
Currently the code generator generates an empty `const (...)` when there
are no errors defined in the API. This will be removed by `gofmt` but
it is frequent to forget to run it when the SDK is updated, and as a
result those pull requests are rejected. To avoid that this patch
changes the code so that it doesn't generate that empty `const`.
> Don't generate empty set of constants for errors

- CHANGES.adoc
- pkg/info/info.go
- Keep concepts sorted by name.
- Don't generate empty `const` block for errors.
- Add `Copy` method to builders.
> Release 0.0.7

- tests/builders_test.go
- tests/readers_test.go
- tests/servers_test.go
- tests/types_test.go
This patch changes the tests so that they use `cmv1` instead of `v1` as
the package selector for the API packages. This will simplify
introduction of other API packages in future patches.
> Use `cmv1` instead of `v1` as package selector

- pkg/generators/builders.go
- pkg/generators/readers.go
- pkg/generators/types.go
- pkg/golang/types.go
- tests/builders_test.go
- tests/client_tests.go
- tests/model/accounts_mgmt/v1/auth_type.model
- tests/readers_test.go
- tests/types_test.go
- tests/writers_test.go
This patch improves the support for attributes whose type is a map where
the key is a string and the value is an struct. This means that now
types like the following can be used:
```
struct AccessToken {
Auths [string]Auth
}
struct Auth {
Username string
Email string
}
```
The JSON representation for these types will be like this:
```json
{
"auths": {
"my.com": {
"username": "myuser",
"email": "mymail"
},
"your.com": {
"username": "youruser",
"email": "yourmail"
}
}
```
In the generated code these types will be built like this:
```go
token, err := amv1.NewAccessToken().
Auths(map[string]*amv1.AuthBuilder{
"my.com": amv1.NewAuth().
Username("myuser").
Email("mymail"),
"your.com": amv1.NewAuth().
Username("youruser").
Email("yourmail"),
}).
Build()
if err != nil {
...
}
```
> Improve map support

- pkg/generators/servers.go
- tests/servers_test.go
Currently the names for adapters are like `RootServerAdatper`. As
adapters are only used for servers there is no need for the extra
_server_ word there. This patch changes the code generator so that the
names will be like `RootServer`.
> Generate shorter adapter names

- pkg/generators/servers.go
Currently the generated code contains string constants like `POST` and
`GET` in multiple places. This patch changs the code generator so that
it uses the constants from the Go `net/http` package instead.
> Use constants from the `http` package

- pkg/generators/servers.go
- pkg/nomenclator/names.go
This patch changes the code generator so that it produces shorter names
for the methods that requests and write responses.
> Shorter _read_ and _write_ names

- pkg/generators/servers.go
- tests/servers_test.go
Currently the code generated for servers requires implementations to set
a status code, otherwise it will be 0 and the Go HTTP library will
generate an error. To avoid that this patch changes the generated code
so that it always sets a default value.
> Set default status

- CHANGES.adoc
- pkg/info/info.go
- Generate shorter adapter names.
- Use constants from the `http` package.
- Shorter _read_ and _write_ names.
- Rename `SetStatusCode` to `Status`.
- Improve naming of variables.
- Set default status.
- Move errors and helpers generators to separate files.
> Release 0.0.9

- go.mod
- go.sum
- pkg/concepts/resource.go
- pkg/generators/errors.go
- pkg/generators/helpers.go
- pkg/generators/servers.go
- pkg/nomenclator/names.go
- tests/servers_test.go
Currently the adapters that convert HTTP requests into requests to the
implementations of th servers are stateful: they contain a reference to
the server that they use. This means that each request requires the
allocation of a new adapter for each path segment. To avoid that
unnecessary allocations this patch changes the adapters so that they are
stateless functions instead of objects.
> Stateless adapters

- CHANGES.adoc
- pkg/info/info.go
- Make HTTP adapters stateless.
> Release 0.0.10

- pkg/generators/errors.go
- pkg/generators/servers.go
Currently the generated code sends a 409 code when a method is not
supported, but it should send 405 instead. This patch fixes that.
> Fix the method not allowed code

- pkg/generators/servers.go
- tests/model/clusters_mgmt/v1/nil_resource.model
- tests/servers_test.go
Currently the HTTP adaters don't check if the value returned by locators
is `nil`. That results in a panic when that happens. To avoid that this
patch changes the generated code so that will check if the returned
value is `nil` and will send a 404 error response if it is.
> Send not found when server returns nil target

- pkg/asciidoc/buffer.go
- pkg/golang/buffer.go
Currently the files created by the code generators have execution
permission, but they don't need it. This patch fixes that.
> Don't generate files with execution permission

- CHANGES.adoc
- pkg/info/info.go
- Improve parsing of initialisms.
- Fix the method not allowed code.
- Send not found when server returns `nil` target.
- Generate service and version servers.
- Don't generate files with execution permission.
> Release 0.0.11

- cmd/ocm-metamodel-tool/generate/cmd.go
- pkg/generators/builders.go
- pkg/generators/clients.go
- pkg/generators/errors.go
- pkg/generators/helpers.go
- pkg/generators/openapi.go
- pkg/generators/readers.go
- pkg/generators/servers.go
- pkg/generators/types.go
- pkg/golang/buffer.go
- pkg/golang/names.go
- pkg/golang/packages.go
- pkg/golang/types.go
- pkg/openapi/buffer.go
Currently the code generators receive as a parameter the base package
and also the packages calculator. To simplify that this patch moves the
base package to the packages calculator and remove it from all the
generators.
> Replace base package with calculator

- pkg/openapi/buffer.go
This patch changes renames the `openAPI` variable that contains the
_OpenAPI_ specification to `OpenAPI` so that it will be public.
> Make OpenAPI specification public

- CHANGES.adoc
- pkg/info/info.go
- Add `Poll` method to clients that have a `Get` method.
> Release 0.0.14

- pkg/generators/clients.go
- pkg/generators/docs.go
- pkg/generators/openapi.go
- pkg/generators/readers.go
- pkg/generators/types.go
- pkg/nomenclator/names.go
- tests/client_test.go
- tests/poll_test.go
This patch adds support for retrieving the metadata of a service
version. This is done via the root resource of that version which will
have a `Get` method that retrieves an object of type `Metadata`. For
example:
```
// Get the client for the root resource:
client := connection.ClustersMgmt().V1()
// Send the request to retrieve the metadata:
response, err := client.Get().Send()
if err != nil {
...
}
metadata := response.Body()
// Print some metadata details:
fmt.Printf("server version: %s\n", metadata.ServerVersion())
```
> Add version metadata support

- pkg/asciidoc/main_test.go
- pkg/asciidoc/markdown.go
- pkg/asciidoc/markdown_test.go
- pkg/asciidoc/tests/blocks.adoc
- pkg/asciidoc/tests/blocks.md
- pkg/asciidoc/tests/headers.adoc
- pkg/asciidoc/tests/headers.md
- pkg/generators/openapi.go
This patch adds a versy simple (and limited) mechanism to convert
_AsciiDoc_ to _Markdown_. This is intended only for conversion of the
documents used in the generated _OpenAPI_ specification.
> Add simple conversion from AsciiDoc to Markdown

- pkg/concepts/method.go
- pkg/concepts/resource.go
- pkg/language/checks.go
- pkg/language/reader.go
- pkg/nomenclator/names.go
- pkg/reporter/reporter.go
- tests/model/clusters_mgmt/v1/cluster_resource.model
- tests/model/clusters_mgmt/v1/clusters_resource.model
- tests/model/clusters_mgmt/v1/groups_resource.model
- tests/model/clusters_mgmt/v1/identity_providers_resource.model
- tests/model/clusters_mgmt/v1/users_resource.model
This patch adds some initial semantic checks. For example it adds a
check to verify that the `Total` parameter of the `List` methods is
`out` only.
> Add semantic checks

- pkg/language/checks.go
- tests/model/clusters_mgmt/v1/groups_resource.model
- tests/model/clusters_mgmt/v1/identity_providers_resource.model
- tests/model/clusters_mgmt/v1/users_resource.model
This patch adds checks to ensure that the `Page` parameter has `1` as
the default value and that the `Size` parameter has a default value.
> Check default values of paging parameters

- pkg/generators/openapi.go
This patch adds the stage URL and the `securitySchemes` component to the
generated _OpenAPI_ specifications.
> Add stage URL and `SecuritySchemes` to _OpenAPI_

- pkg/generators/readers.go
Currently reading an object fails if the `kind` attribute isn't one of
the expected ones. But the server tends to report this incorrectly, and
the SDK doesn't really need the `kind` attribute to figure out the type
of the object. To make the SDK more tolerant of server inconsistences
this patch changes the generated code so that it will not require a
correct value for the `kind` attribute.
> Don't fail on wrong kind

- CHANGES.adoc
- pkg/info/info.go
> Release 0.0.19

- pkg/generators/errors.go
- tests/readers_test.go
- tests/writers_test.go
Currently the code that converts errors to JSON doesn't write the `kind`
attribute. This patch fixes that.
> Fix marshal of errors

- CHANGES.adoc
- pkg/info/info.go
- Fix conversion of errors to JSON so that the `kind` attribute is generated
correctly.
> Release 0.0.20

- tests/readers_test.go
This patch adds a test that verifies tht wrong values of the `kind`
attribute are ignored.
> Test that wrong kind is ignored

- tests/readers_test.go
This patch adds a test that checks that unknown attributes are ignored.
> Test ignore unknown attributes

- tests/marshal_test.go
- tests/unmarshal_test.go
This patch adds tests that verify the marshal and unmarshal of lists of
scalar types.
> Add list marshal and unmarshal tests

- CHANGES.adoc
- pkg/info/info.go
- Use JSON interator instead of the default JSON Go package.
> Release 0.0.21

- pkg/generators/openapi.go
Currently path segments for locators without variables are generated
using the string representation of the name. That results in some names
containing acronyms in uppercase. For example:
```
"/api/clusters_mgmt/v1/clusters/{cluster_id}/metric_queries/socket_total_by_node_roles_OS": {
...
}
```
That last path segmet should be `socket_total_by_node_roles_os`.
This patch changes the OpenAPI generator so that it uses the right rules
to generate those path segments.
> Fix OpenAPI paths

- CHANGES.adoc
- pkg/info/info.go
- Fix generation of _OpenAPI_ paths so that all the characters are lower case.
> Release 0.0.22

- pkg/concepts/version.go
Currently the code that generates OpenAPI paths uses the `append`
function to extend the generated paths inside an iterative algorithm.
This results in some of the generated paths (which are slices of
pointers to objects) sharing the same underlying array. When the slice
is modified via any of those slides that share the underlying array the
generated path overwrites an existing one, resulting in duplicated and
missing paths. This patch addresses that issue replacing that use of
`append` with a combination of `make` and `copy`.
> Fix generation of OpenAPI paths

- pkg/generators/golang/json_generator.go
This patch changes the generated code so that server responses contain
the required `Content-Type` header.
> Add `Content-Type` to server responses

- pkg/generators/golang/servers_generator.go
- tests/go/servers_test.go
Currently the main _Dispatch_ method of the server requires the
developer to explicitly strip the `/api` prefix from URLs. This patch
fixes that.
> Don't require prefix strip

- cmd/generate/golang/cmd.go
- pkg/generators/golang/buffer.go
Currently the code generator runs the _goimports_ tool once for each
generated file. To reduce the overhead of running it multiple times this
patch changes the code generator so that it runs it only once after all
the source files have been generated.
> Run _goimports_ only once

- pkg/generators/golang/json_generator.go
This patch changes the Go code generator so that it avoid constructs
that the `govmt -s` command would simplify. Without this running `make
fmt` in the SDK project modifies generated code which is then rejected
by the tests that check that modified code ins't modified manually.
> Avoid `gofmt -s` changes

- CHANGES.adoc
- pkg/info/info.go
- Run the `gofmt` command only once for all generated files instead of running
it once per each generated file.
- Avoid generating code with constructs that would then be simplified by the
`-s` flag of the `gofmt` command.
> Release 0.0.25

- pkg/generators/golang/errors_generator.go
- tests/go/builders_test.go
- tests/go/errors_test.go
- tests/go/marshal_test.go
- tests/go/unmarshal_test.go
This patch changes the code generator so that errors support the
`operation_id` attribute. This attribute and the existing ones will now
be used to generate more complete error messages. For example, the
following JSON error response:
```json
{
"kind": "Error",
"id": "401",
"href": "/api/clusters_mgmt/v1/errors/401",
"code": "CLUSTERS-MGMT-401",
"reason": "My reason",
"operation_id": "456"
}
```
Will result in the following error string (in one single line):
```
identifier is '401', code is 'CLUSTERS-MGMT-401' and
operation identifier is '456': My reason
```
Related: https://github.com/openshift-online/ocm-sdk-go/issues/150
> Add `operation_id` to errors

- pkg/generators/golang/buffer.go
It's time to update this file header copyright notice. This gives us 8 more months before we need to worry about it again :calendar:
> Update file header year to 2020

- CHANGES.adoc
- pkg/info/info.go
- Update file header year to 2020
> Release 0.0.27

- pkg/http/binding_calculator.go
When generating the OpenAPI specification, PATCH operations are set to
respond with 204: No Content, but the API Model expects the payload to
be sent. The Clusters Service also sends the payload on PATCH in most,
but not all, endpoints. This causes several issues:
* OpenAPI spec documentation shows a 204 response _with_ a response body
* Clusters Service has inconsistent responses for PATCH operations
* The SDK fails at unmarshaling the cluster response on update
> OpenAPI: Fix expected response

- pkg/generators/golang/clients_generator.go
When generating Polling request clients with query parameters, the setter
needs to defer to the correct Get method to set values.
> Fix setter for Poll request params

- pkg/concepts/type.go
- pkg/concepts/version.go
- pkg/generators/golang/json_generator.go
- pkg/generators/golang/types_calculator.go
- pkg/generators/golang/types_generator.go
- pkg/generators/openapi/openapi_generator.go
- pkg/nomenclator/names.go
There are instances where we need the SDK to allow attributes of type
interface{} in the API. In this case we can treat the value as
a nullable scalar type and generate it without the pointer indirection.
> generator: Add interface type

- pkg/language/checks.go
@zvikorn - I've fixed the errors when building the SDK. This is the relevant part of the generated OpenAPI:
```diff
"/api/clusters_mgmt/v1/clusters/{cluster_id}/ingresses": {
@@ -2496,6 +2546,55 @@
}
}
}
+      },
+      "patch": {
+        "description": "Updates all ingresses\n",
+        "parameters": [
+          {
+            "name": "cluster_id",
+            "in": "path",
+            "schema": {
+              "type": "string"
+            }
+          }
+        ],
+        "requestBody": {
+          "content": {
+            "application/json": {
+              "schema": {
+                "type": "array",
+                "items": {
+                  "$ref": "#/components/schemas/Ingress"
+                }
+              }
+            }
+          }
+        },
```
> Adding List type to checkUpdate validator

- pkg/generators/golang/json_generator.go
To support returning 204 No Content as a response to a POST request
(e.g. when using a --dry-run parameter), we check that the source object
has no body and return early. This avoids the iterator from panicking on
iterating through an empty payload.
> json: Support NoContent on POST responses

- pkg/names/case.go
- pkg/names/parser_test.go
When determining field names with digits, we should treat them as part
of an initialism. Otherwise numeric values end up as part of their own
word part and generate repeating components in field names.
> names: Support numeric initialisms

- pkg/asciidoc/buffer.go
- pkg/generators/golang/buffer.go
This patch changes the calls to `fmt.Errorf` so that they use `%w` instead of
`%v` for errors.
> Wrap errors

- pkg/concepts/attribute.go
- pkg/concepts/error.go
- pkg/concepts/locator.go
- pkg/concepts/method.go
- pkg/concepts/named.go
- pkg/concepts/parameter.go
- pkg/concepts/resource.go
- pkg/concepts/service.go
- pkg/concepts/type.go
- pkg/concepts/version.go
- pkg/names/named.go
This patch adds a new `documentedSupport` and `namedSupport` types that are
embedded in all types that need to implement the `Documented` and `Named`
interface. This reduces the duplication of code associated to the
implementation of those interfaces.
> Add `documentedSupport` and `namedSupport`

- pkg/concepts/attribute.go
- pkg/concepts/parameter.go
- pkg/concepts/typed.go
This patch adds a new `typedSupport` to avoid repeating the implementation of
the `Type` and `GetType` methods.
> Add `typedSupport`

- cmd/check/cmd.go
- cmd/generate/docs/cmd.go
- cmd/generate/golang/cmd.go
- cmd/generate/openapi/cmd.go
- pkg/reporter/reporter.go
This patch changes the reporter so that the streams it uses to write messages
are configurable. This is intended for use in tests, where we will want to
write to the output of the testing framework instead of to the standard output.
> Make reporter streams configurable

- go.mod
- go.sum
- pkg/generators/golang/builders_generator.go
- pkg/generators/golang/errors_generator.go
- pkg/generators/golang/json_generator.go
- pkg/generators/golang/types_calculator.go
- pkg/generators/golang/types_generator.go
- tests/go/types_test.go
This patch changes the generated code so that instead of using pointers to
store attributes of scalar values (strings, integers, etc) it stores them
directly and uses a bitmap to keep track of which attributes are present. This
reduces the use of CPU and the number of allocations. In a test that loads 1
million clusters in memory it reduces CPU by approx 20% and memory by approx
10%.
> Add presence bitmap

- cmd/generate/golang/cmd.go
- pkg/generators/golang/buffer.go
- pkg/generators/golang/clients_generator.go
- pkg/generators/golang/helpers_generator.go
- pkg/generators/golang/metrics_generator.go
- pkg/generators/golang/packages_calculator.go
- pkg/nomenclator/names.go
- tests/go/clients_test.go
- tests/go/poll_test.go
This patch adds a new code generator that generates the
`path_tree_data.go` file containing the tree of URL paths that the
metrics round tripper of the SDK will use to calculate the `path` label
of metrics. This means that it is no longer necessary to use the
`X-Metric` header to carry the value of that label, so the patch also
removes all uses of that header.
> Add metrics support generator

- pkg/generators/golang/servers_generator.go
Currently the generated server code uses the `glog` package, but we
don't have a explicit import. As a result when we run `goimports` it
tries to fix that. It used to select `github.com/golang/glog` but
recently it has started to select `github.com/istio/glog` instead. That
causes conflict in the projects that use the generated code together
with the `github.com/istio/glog` package, generating errors like this:
```
go: github.com/istio/glog@v0.0.0-20190424172949-d7cfb6fa2ccd used for
two different module paths (github.com/golang/glog and github.com/istio/glog)
```
To address that this patch changes the code generators so that they
explicitly import the `github.com/golang/glog` package.
> Explicitly import `glog`

- CHANGES.adoc
- pkg/info/info.go
- Explicitly import `github.com/golang/glog` to avoid conflicts with
`github.com/istio/glog`.
> Release 0.0.38

- pkg/generators/golang/errors_generator.go
- tests/go/builders_test.go
- tests/go/marshal_test.go
- tests/go/unmarshal_test.go
Part of : https://issues.redhat.com/browse/SDA-4587
This change adds details object to errors
> SDA-4587 : add details to errors

- CHANGES.adoc
- pkg/info/info.go
- Add `details` attribute to errors.
> Release 0.0.39

- .github/workflows/publish-release.yaml
The action that publishes releases was uploading artifacts using the
`--data` option of the `curl` tool. That results in processing them as
ASCII and limits the size to approximately 4 MiB. The end result is that
the uploaded binaries don't work. This patch fixes that using the
`--data-binary` option instead.
> Fix publish release action

- CHANGES.adoc
- pkg/info/info.go
The only change in this release is that the _GitHub_ action that
publishes releases has been fixed so that it publishes correct binaries.
There are no changes in functionality.
> Release 0.0.41

- CHANGES.adoc
- pkg/info/info.go
- Accept iterator as parameter in `helpers.NewIterator`.
> Release 0.0.42

- pkg/generators/golang/clients_generator.go
- pkg/generators/golang/errors_generator.go
- tests/go/clients_test.go
- tests/go/errors_test.go
This patch adds a new `status` attribute to errors, which is
automatically populated with the HTTP status code returned by the
server.
> Add `status` attribute to errors

- CHANGES.adoc
- pkg/info/info.go
The only relevant change in the new version is the addition of the
`status` attribute to errors.
> Release 0.0.43

- pkg/generators/golang/builders_generator.go
- tests/go/builders_test.go
This patch adds a new `Empty` method to builders that simplifies
checking if any attribute has been set.
> Add `Empty` method to builders

- CHANGES.md
- pkg/info/info.go
The only functional change in this version is the change from _Markdown_ to
_AsciiDoc_. That is not really relevant because the generated documentation
isn't currently published.
In addition to that there also some changes to the development and build
workflows:
- Rename `master` branch to `main`.
To adapt your local repository to the new branch name run the following
commands:
```shell
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
- Rewrite the publish release action in _Python_.
- Automatically add changes from `CHANGES.md` to release descriptions.
> Release 0.0.45

- pkg/generators/golang/errors_generator.go
- pkg/generators/golang/json_generator.go
This patch changes the generated code so that it checks the errors
retuned from the `Flush` method of JSON streams.
> Check result of flush

- pkg/generators/golang/helpers_generator.go
This patch changes the `PollContext` function so that it always cancels
the deadline context that it creates.
> Canel poll context

- pkg/generators/golang/json_generator.go
- pkg/generators/golang/servers_generator.go
- pkg/generators/openapi/buffer.go
If the `jsoniter` package selector then the import is removed by some
combinations of the Go compiler and the `goimports` tool.
> Expliclty use `jsoniter` package selector

- CHANGES.md
- pkg/info/info.go
The more relevant changes in the new release are the following:
- Remove unused imports.
- Check result of `Flush` method.
- Cancel poll context.
- Avoid some ineffectual assigments.
- Explicitly use `jsoniter` package selector.
> Release 0.0.46

- CHANGES.md
- pkg/info/info.go
- Update to Go 1.17.
- Update to Ginkgo 2.
- Update to ANTLR 4.9.3.
- Update Go dependencies.
- Simplify installation with `go install` so that it will be possible to
install the `metamodel` tool with a command like this:
```
go install github.com/openshift-online/ocm-api-metamodel/cmd/metamodel@v0.0.47
```
> Release 0.0.47

- .github/workflows/publish-release.yaml
Currently the release process assumes that the name of the binary file
is `metamodel`, but in Windows it is `metamodel.exe`. As a result the
release process fails because it doesn't find the asset to upload. This
patch fixes that issue.
> Fix release of windows artifacts

- pkg/generators/golang/helpers_generator.go
- tests/go/clients_test.go
- tests/go/servers_test.go
- tests/model/status_board/v1/root_resource.model
- tests/model/status_board/v1/status_type.model
- tests/model/status_board/v1/statuses_resource.model
Currently query parameters that are dates are formatted using the
default Go format, but they should be formatted using RFC3389 format.
This patch fixes that.
> Fix format of date query parameters

- CHANGES.md
- pkg/info/info.go
- Fix format of date query parameters so that it is RFC3339.
> Release 0.0.50

- pkg/generators/golang/clients_generator.go
- pkg/generators/golang/json_generator.go
- tests/go/clients_test.go
- tests/go/main_test.go
Currently the clients always try to parse the HTTP response body, even
when it is empty. The `Unmarshal...` methods used for that compare the
reader to `http.NoBody` and return nil in that case. This isn't reliable
because transport wrappers may use a different type to indicate an empty
response body. To avoid that this patch replaces that check with a
buffered reader. This is used to peek the first byte of the response
body and then check if it results in `io.EOF`. This approach should work
regardless of the type of the response body.
> Check for `io.EOF` before trying to parse response body

- CHANGES.md
- pkg/info/info.go
- Check for `io.EOF` before trying to parse response body.
> Release 0.0.51

- pkg/http/binding_calculator.go
- tests/go/clients_test.go
- tests/go/servers_test.go
- tests/go/unmarshal_test.go
- tests/model/clusters_mgmt/v1/cluster_type.model
- tests/model/clusters_mgmt/v1/root_resource.model
The `@json` annotation is used to set an alternative name for attributes
and parameters in JSON representations. For example, if an attribute is
defined line this:
```
attribute CPUID string
```
The generated code will use `cpuid` in the JSON representation. This may
be incorrect if the intent was to use two separate words `CPU` and `ID`.
the annotation can be used to tell the code generator to use `cpu_id`
instead:
```
@json(name = "cpu_id")
attribute CPUID string
```
The `@http` annotation is similar, but intended for segments of URLs
corresponding to methods, locators and query parameters.
> Add `@json` and `@http` annotations

- pkg/names/name.go
- pkg/names/parser.go
This patch adds to the `names.Name` type a new field to store the
original text that was used to create it.
> Add original text to name

- README.md
- pkg/generators/golang/clients_generator.go
- pkg/generators/golang/helpers_generator.go
This call enables clients with appropriate permissions to make requests
on behalf of a different user. It is important to note that not all
services support impersonation calls.
> adding Impersonate method for requests.

- .github/workflows/check-pull-request.yaml
This patch changes the GitHub actions so that pull requests for the `v2`
branch are also checked.
> Check `v2` pull requests

- pkg/generators/golang/clients_generator.go
- pkg/generators/golang/helpers_generator.go
- tests/go/clients_test.go
- tests/go/poll_test.go
This patch removes the code that generates the methods that send
requests without a context. It will no mandatory to use the `Send`
method with a context, and the `SendContext` method is removed.
> Remove send without context

- CHANGES.md
- pkg/info/info.go
The more relevant changes in the new release are the following:
- Don't consider `Status` and `Error` built-in request parameters.
> Release 0.0.53

- pkg/generators/openapi/openapi_generator.go
1.
"details": {
"description": "Extra information about the error.",
"type": "object",
"additionalProperties": "true"
}
but according to openapi scheme it must be
"additionalProperties": true
which is default anyway. This is from openapi spec:
additionalProperties - Value can be boolean or object. Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema. Consistent with JSON Schema, additionalProperties defaults to true.
2.
invalid paths: invalid path /api/clusters_mgmt/v1/addons/{addon_id}: invalid operation DELETE: path parameter "addon_id" must be required
> [SDB-3474] Generated openapi json has the following problems

- pkg/generators/golang/clients_generator.go
- pkg/generators/golang/json_generator.go
- pkg/generators/openapi/openapi_generator.go
- pkg/http/binding_calculator.go
- tests/go/clients_test.go
- tests/model/clusters_mgmt/v1/clusters_resource.model
Currently the `@http` annotation is ignored for query parameters. We are using `@json` instead. That is a bug, and this patch fixes it.
> Honor `@http` annotation for query parameters

- CHANGES.md
- pkg/info/info.go
- Honor `@json` annotation in query parameters.
> Release 0.0.59

- .github/workflows/check-pull-request.yaml
- .gitignore
- Makefile
Update makefile:
- Add ginkgo-install and goimports-install
- Add binary gen for necessary targets
- Add bin dir for all built of required binaries
- Add absolute path to the bin dir
> Update makefile: Add ginkgo-install and add binary gen for necessary targets

- pkg/annotations/annotations.go
- pkg/concepts/type.go
- pkg/concepts/version.go
- pkg/generators/golang/builders_generator.go
- pkg/generators/golang/json_generator.go
- pkg/generators/golang/types_calculator.go
- pkg/generators/golang/types_generator.go
- pkg/language/checks.go
- pkg/language/reader.go
- pkg/language/ref_test.go
- tests/model/aro_hcp/v1_alpha1/cluster_resource.model
- tests/model/aro_hcp/v1_alpha1/cluster_type.model
- tests/model/aro_hcp/v1_alpha1/clusters_resource.model
- tests/model/aro_hcp/v1_alpha1/node_pool_resource.model
- tests/model/aro_hcp/v1_alpha1/node_pool_type.model
- tests/model/aro_hcp/v1_alpha1/node_pools_resource.model
- tests/model/aro_hcp/v1_alpha1/root_resource.model
- tests/model/clusters_mgmt/v1/node_pool_type.model
Adds support for a reference directive -  `@ref(name="/path/to/service")`  in order to share resources and definitions between services.
Currently this is only supported for types in order to share their definition between services, however, as we continue to implement the `/aro_hcp` service we will likely enhance this implementation.
[Here](https://github.com/openshift-online/ocm-api-model/pull/1006) is an example use case where we share the Cluster type:
```
@ref(path = "/clusters_mgmt/v1/cluster")
class Cluster {
}
```
With sdk that looks like the following:
```
It("Check for duplicate cluster name with same Azure Resource Name", func() {
postBody, err := arohcphelper.GetAroHCPClusterBuilder(azureBuilder, westUs3, properties).Build()
helper.CheckError(err)
postResponse, err := …
```
> Add support for 'ref' annotation

- pkg/generators/golang/types_generator.go
These return statements are triggering the sdk linter.
> Remove redundunt return triggering lint

- pkg/concepts/version.go
- pkg/language/reader.go
These are now redundant as we have now moved away from relying on type ownership [see #214].
cc @ahitacat
> Revert redundunt code changes

- pkg/concepts/method.go
- pkg/concepts/parameter.go
- pkg/generators/docs/docs_generator.go
- pkg/generators/golang/json_generator.go
- pkg/http/binding_calculator.go
- pkg/language/checks.go
- pkg/nomenclator/names.go
Asynchronous methods require a StatusAccepted as a response. This commit adds 2 new async methods (delete and update) that will be used on v2 of cluster_mgmt.
> ARO-9390: Add asynchronous methods

- pkg/language/reader.go
- pkg/language/ref_test.go
When adding the version_type.model [PR](https://github.com/openshift-online/ocm-api-model/pull/1041]) definition to aro_hcp the metamodel fails to generate read it with the following error:
```
E: Type 'Version' is already defined
E: Can't read model: there was 1 error
make: *** [Makefile:53: openapi] Error 1
```
This is due to '`version`' is already part of the service as it was previously read (via node pool), and when reading the definition for '`version`' in `aro_hcp` service it fails. 
This commit fix this case, by checking if an defined type has the reference annotation. In this case, it sets this type as an ExplicitDeclared type and fix the ownership in the attributes that the reader has already read.
> OCM-16102: fix reference class already defined

- cmd/metamodel/generate/golang/cmd.go
- pkg/generators/golang/builders_alias_generator.go
- pkg/generators/golang/json_alias_generator.go
IOUs from https://github.com/openshift-online/ocm-api-metamodel/pull/219
/assign @ahitacat @nimrodshn
> add clarifying comments for new generators and aliased functions

- OWNERS
This commit:
- Removes mnecas from the approves/reviwers as @mnecas is no longer part of the team (:crying_cat_face: ). I have move him to emeritus_approvers section.
- Cleans unnecessary comments
> OWNERS file sanity

- pkg/annotations/annotations.go
- pkg/annotations/annotations_test.go
- pkg/annotations/main_test.go
- pkg/generators/openapi/openapi_generator.go
> OCM-17280 | feat: Add support for deprecated annotation

- pkg/generators/golang/types_generator.go
- pkg/language/checks.go
- pkg/language/checks_test.go
@jhernand @nimrodshn @ahitacat
> chore: Add validation (check) and block adding 'id' field to a class
