- CHANGES.adoc
- pkg/info/info.go
- Added new `check` command that loads and checks the model but doesn't
generate any code.
> Release 0.0.2

- CHANGES.adoc
- pkg/info/info.go
> Release 0.0.4

- pkg/generators/servers.go
The `query` and `path` fields of request types aren't needed. This
patch removes them.
> Remove `query` and `path` fields from requests

- pkg/generators/servers.go
This patch removes some imports that aren't used by the generate servers
code.
> Remove not used imports

- CHANGES.adoc
- pkg/info/info.go
- Use a private model for tests.
- Improve support for maps of objects.
> Release 0.0.8

- pkg/generators/clients.go
- pkg/generators/servers.go
- pkg/golang/buffer.go
- pkg/names/parser.go
- pkg/names/words.go
- tests/servers_test.go
- tests/types_test.go
This patch adds to the servers code generator the capability to generate
the interfaces and HTTP adapters for service and version servers.
> Generate service and version servers

- CHANGES.adoc
- pkg/info/info.go
- Add _OpenAPI_ specification generator.
> Release 0.0.12

- pkg/generators/clients.go
- pkg/generators/errors.go
- pkg/generators/servers.go
This patch fixes the imports of the `helpers` and `errors` packages.
> Fix imports of helpers and errors

- pkg/concepts/resource.go
- pkg/generators/clients.go
- pkg/generators/helpers.go
- pkg/nomenclator/names.go
- tests/client_test.go
- tests/main_test.go
- tests/model/clusters_mgmt/v1/cluster_type.model
- tests/poll_test.go
This patch adds to all resources that have a `Get` method a new `Poll`
method that retrieves repeatedly the resource till the response has
certain status and till certain conditions are satisfied.
> Add `Poll` method

- CHANGES.adoc
- pkg/info/info.go
- Add support for the version metadata resource.
> Release 0.0.15

- CHANGES.adoc
- pkg/info/info.go
- Add simple conversion from AsciiDoc to Markdown.
> Release 0.0.16

- pkg/concepts/parameter.go
- pkg/generators/readers.go
- pkg/generators/servers.go
- pkg/language/ModelParser.g4
- pkg/language/checks.go
- pkg/language/reader.go
- pkg/reporter/reporter.go
- tests/model/clusters_mgmt/v1/cluster_resource.model
- tests/model/clusters_mgmt/v1/clusters_resource.model
- tests/servers_test.go
This pach adds support for specifing default value of parameters of
methods.
> Add support for default values

- CHANGES.adoc
- pkg/info/info.go
- Add semantic checks.
- Add support for default values.
- Check default values of paging parameters.
> Release 0.0.17

- CHANGES.adoc
- pkg/info/info.go
- Add stage URL and `securitySchemes` to the generated _OpenAPI_
specifications.
> Release 0.0.18

- CHANGES.adoc
- pkg/info/info.go
- Add `Content-Type` to responses sent by the generated server code.
- Don't require developer to explicitly remove the `/api` when using the
server code.
- Remove redundant quotes from error responses sent by the generated
server code.
> Release 0.0.24

- CHANGES.adoc
- pkg/info/info.go
- OpenAPI: Fix expected response
> Release 0.0.28

- CHANGES.adoc
- pkg/info/info.go
- pr_check: Lock in dependency versions for test pipeline
- Fix setter for Poll request params
> Release v0.0.29

- CHANGES.adoc
- pkg/info/info.go
- Adding List type to checkUpdate validator
> Release v0.0.31

- CHANGES.adoc
- pkg/info/info.go
- json: Support NoContent on POST responses
> Release v0.0.33

- CHANGES.adoc
- pkg/info/info.go
- names: Support numeric initialisms
> Release v0.0.34

- CHANGES.adoc
- pkg/info/info.go
- Update to version 4.8 of Antlr
- Wrap errors
> Release v0.0.35

- CHANGES.adoc
- pkg/info/info.go
- Use Go 1.15
- Add `documentedSupport` and `namedSupport`
- Add `typedSupport`
- Make reporter streams configurable
- Add presence bitmap
> Release v0.0.36

- CHANGES.adoc
- pkg/info/info.go
The more relevant changes are the following:
- Add metrics support generator, and remove `X-Metric` header.
> Release 0.0.37

- pkg/generators/golang/clients_generator.go
This patch removes some generated code that isn't used.
> Remove unused code

- pkg/language/checks.go
Currently the model parser doesn't check for loops in the graph of
locators. This can cause infinite loops or stack overflows in tools that
process it, in particular in the tool that generates the tree of URL
segments used for metrics. To avoid that this patch introduces an
additional check for that. When it detects a loop it print an error
message and abort the processing. For example, with a simple recursive
locator like this:
```
resource A {
locator A {
target A
}
}
```
It will print the following error message:
```
E:Locator 'A' introduces a loop, it is defined in resource 'MyService.V1.A' and targets that same resource
```
For a more compliated loop like this:
```
resource A {
locator B {
target B
}
}
resource B {
locator C {
target C
}
}
resource C {
locator A {
target A
}
}
```
It …
> Check loops in locator paths

- CHANGES.adoc
- pkg/info/info.go
- Check loops in locator paths.
- Add `Empty` method to builders.
> Release 0.0.44

- cmd/generate/golang/cmd.go
> Spelling fix

- .github/workflows/publish-release.yaml
- .github/workflows/requirements.txt
This patch rewrites the publish release action in Python, so that it
will be easier to improve it in the future.
> Rewrite publish release action in Python

- .github/workflows/publish-release.yaml
This patch changes the publish release workflow so that it extracts the
list of changes from the `CHANGES.md` file and adds them to the
description of the release.
> Add changes to releases

- pkg/generators/golang/clients_generator.go
This patch removes some unused imports from the templates that generate
the client code.
> Remove unused imports

- pkg/generators/golang/buffer.go
- pkg/generators/golang/json_generator.go
This patch changes the code generator so that it avoid some inefectual
assignments in the generated code.
> Avoid some ineffectual assignments in generated code

- CHANGES.md
- pkg/info/info.go
This release doesn't include any change in functionality, it only fixes the
script that releases Windows artifacts.
> Release 0.0.48

- CHANGES.md
- pkg/info/info.go
The more relevant changes in this release are the following:
- Add support for annotations.
- Add `@json` and `@http` annotations.
- Add `@go` annotation.
- Add original text to names.
- Add `Impersonate` method to support the `Impersonate-User` header.
> Release 0.0.52

- pkg/generators/golang/clients_generator.go
- pkg/generators/golang/openapi_generator.go
- pkg/language/main_test.go
- pkg/language/model_parser.go
- pkg/language/reader.go
> Fix linter issues in sdk for generated clients - remove dependency in ioutils

- CHANGES.md
> Update changes doc

- CHANGES.md
- pkg/info/info.go
> Release version 0.0.56

- CHANGES.md
- pkg/info/info.go
- Add support for `ref` annotation
> chore: Release 0.062

- CHANGES.md
- pkg/info/info.go
- Revert redundunt code changes.
- Fix ownership issue
> Release v0.0.63

- CHANGES.md
- pkg/info/info.go
- Enhancement of 'ref' mechanism
- Change the tests for ref subresources
> Release v0.0.65

- Makefile
- OWNERS
- hack/verify-gofmt.sh
Strictly additive.  OWNERS based on the repo collaborator settings.
> Add OWNERS and a verify script for vet and fmt

- Makefile
this will produce nice spyglass results.
> use ginkgo junit.xml output
